### ISSUE TITLE
multiple cameras with the same module

### ISSUE THREAD

**Issue by eithwa** [eYs3D/eys3d_ros#4]
I use two g53 cameras and give them different namespaces, but get this error on startup
```
I/eSPDI_API: [/dev/video2]start capturing !!
^C09-08 18:26:20.049 31601-31721 [ERROR] CameraDevice:
        Error reading depth image from device, ret=-24
        (/home/ubuntu/python_wrapper_sinet/libeYs3D/src/devices/CameraDevice.cpp:1538:readDepthFrame)

```
I would like to ask if it is possible to turn on two cameras of the same module at the same time?
Also when I get this error, even if I only have one camera on, I have to replug the USB port first to get the camera to work
I want to ask what steps I did wrong, thanks

**Comment by eithwa** [comment]
I found that the usb power of my device is not enough to provide two cameras, the problem is solved now, close the issue

**Comment by Alps-lo** [comment]
Hi Eithwa

We update ROS launch file for  two G53 ,your can try it

Which error is not related,you can ignore

For muti camera ,usb power is very important,spec need min 3.3v to triger

Thanks for your feedback！
