### ISSUE TITLE
device_->enableStream() stuck

### ISSUE THREAD

**Issue by eithwa** [eYs3D/eys3d_ros#5]
https://github.com/eYs3D/eys3d_ros/blob/1dff274a797bc28aec85a0a6e80667f37f3843bb/eys3d_ros/eys3d_ros_ws/src/dm_preview/src/dm_preview_nodelet.cpp#L557

When restarting the dm_preview node, sometimes the program gets stuck in this line and there is no response. 
The only way to use it is to re-plug the camera USB. Is there any solution? What is the problem?

**Comment by Alps-lo** [comment]
Hi eithwa

we never face this problum before ,even open two camera at once,repeat  open and restart.

looks like your platform's USB power might not be enough to open camera.

can you try to use another platform and directly plug-in USB, not by hub, to test problum comes from camera or code.

thanks!

**Comment by eithwa** [comment]
> Hi eithwa
> 
> we never face this problum before ,even open two camera at once,repeat open and restart.
> 
> looks like your platform's USB power might not be enough to open camera.
> 
> can you try to use another platform and directly plug-in USB, not by hub, to test problum comes from camera or code.
> 
> thanks!

hi alps-lo
we only use one camera, It works fine when tested on desktop.
However, when executed on an arm system computer such as raspiberry 4 and rk3328, it may fail to start.
Under normal circumstances, the current of the driver starts from 0A to 0.02A, the maximum current is 0.15A when the current is successful, and 0.11A when it is finally stable; if it fails, the current stops at 0.02A. The power supply problem you mentioned, we tested with an external power supply, the USB power supply will reach 4A, so I think the lack of power supply can be ruled out

https://github.com/eYs3D/eys3d_ros/issues/3
I think this may be a similar problem. In some cases, the camera is detected, but the streaming cannot be started. If it is true that it is because of insufficient power supply, can we add a timeout mechanism to stop the program and notify the problem?
thanks

**Comment by Alps-lo** [comment]
update
because customer's platform is Pi4 which need USB BULK mode(we usually use ISO mode)
so we provide BULK mode FW can solve this issue
if anyone use Pi4 please e-mail to us 
thanks!
