### ISSUE TITLE
how to get g100 raw stereo images

### ISSUE THREAD

**Issue by arenas7307979** [eYs3D/eys3d_ros#6]
hii, how to  get stereo images (2frame) topic through ROS Warpper

**Comment by Alps-lo** [comment]
Hello if you want to see L+R color
as SDK video mode 8 L'+R'+D
just change the launch file like this
color_width:2560
color_height:720
depth_width:1280
depth_height:720
fps:30
and you can see the L+R image link like one image publish by left color topic

currently we can't publish two topic,only this way
