### ISSUE TITLE
8062 camera -> Jetson show image

### ISSUE THREAD

**Issue by jeffrysusanto-itri** [eYs3D/eys3d_ros#9]
Hi,

Thank you very much for posting this repo.
However I am having a bit difficulty in getting either RGB and/or Depth images from 8062 camera.
Is there any particular setting that we need to do before using 8062 on Jetson / linux system?

I have tried eCaptureView on Windows and the 8062 camera worked so the hardware itself should be fine.

Any help/experience on this would be greatly appreciated.

**Comment by Alps-lo** [comment]
Hi Jeffry
Thank you for asking this question, sorry for delay reply.
8062 have one videomode as G100(8036) which is 30fps color without IR dot and depth.

HD 30fps /interleave_mode  /color without IR dot
     arg name="color_width"     value="1280" 
     arg name="color_height"    value="720"  
     arg name="depth_width"     value="1280" 
     arg name="depth_height"    value="720"  
     arg name="framerate"       default="60" 
     arg name="depth_data_type" default="$(arg type_11_bits_interleave_mode)" 

please give it a try,but we will update launch architecture recently, please check it if we update, thank!

**Comment by jeffrysusanto-itri** [comment]
Hi,

Okay got it, I applied the settings that you provided and it worked. Thank you very much for that.
Additional request, could you also please give an example if we want to launch 2 8036 and 1 8062 cameras at the same time? is it possible?
Thank you.

**Comment by Alps-lo** [comment]
Hi Jeffry
for muti cameras launch, please reference 2_G53.launch
you just need copy one more camera setting and update param.
If you don't mind, we can support you by mail, more easy to send you sample code.
fae@eys3d.com
Thanks!

**Comment by jeffrysusanto-itri** [comment]
Okay got it, thank you very much for your replies. I will email you for further questions.
